categories: [Statistics]
description: N-way anova. With ou Without interactions
homepage_url: http://workflow4metabolomics.org
name: anova
owner: lecorguille
remote_repository_url: https://github.com/workflow4metabolomics/anova
