categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and compiles the R package batch version 1.1-4
homepage_url: http://workflow4metabolomics.org
name: package_r_batch_1_1_4
owner: lecorguille
